"""Constants for auth v2 errors, event types, and security enums."""

from __future__ import annotations

# Error codes
AUTH_BAD_REQUEST = "AUTH_BAD_REQUEST"
AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED"
AUTH_FORBIDDEN = "AUTH_FORBIDDEN"
AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
AUTH_TOKEN_VERSION_MISMATCH = "AUTH_TOKEN_VERSION_MISMATCH"
AUTH_RATE_LIMITED = "AUTH_RATE_LIMITED"
AUTH_CONTACT_NOT_FOUND = "AUTH_CONTACT_NOT_FOUND"
AUTH_IDENTITY_MISMATCH = "AUTH_IDENTITY_MISMATCH"
AUTH_EMPLOYEE_INACTIVE = "AUTH_EMPLOYEE_INACTIVE"
AUTH_EMPLOYEE_USER_MAPPING_MISSING = "AUTH_EMPLOYEE_USER_MAPPING_MISSING"
AUTH_PASSWORD_MIGRATION_DEFERRED = "AUTH_PASSWORD_MIGRATION_DEFERRED"
AUTH_LOGIN_COOLDOWN = "AUTH_LOGIN_COOLDOWN"
AUTH_REFRESH_REPLAY_DETECTED = "AUTH_REFRESH_REPLAY_DETECTED"
AUTH_SESSION_BINDING_FAILED = "AUTH_SESSION_BINDING_FAILED"
AUTH_SERVICE_UNAVAILABLE = "AUTH_SERVICE_UNAVAILABLE"
AUTH_SUPREME_ALREADY_INITIALIZED = "AUTH_SUPREME_ALREADY_INITIALIZED"
AUTH_SUPREME_USER_NOT_FOUND = "AUTH_SUPREME_USER_NOT_FOUND"
AUTH_SUPREME_CREATE_DISABLED = "AUTH_SUPREME_CREATE_DISABLED"
AUTH_FLOW_DISABLED = "AUTH_FLOW_DISABLED"

# Audit event outcomes
OUTCOME_SUCCESS = "success"
OUTCOME_FAILURE = "failure"
OUTCOME_SECURITY = "security"

# Audit event types
EVENT_CHECK_CONTACT = "AUTH_V2_CHECK_CONTACT"
EVENT_CHECK_CONTACT_RATE_LIMIT = "AUTH_V2_CHECK_CONTACT_RATE_LIMIT"
EVENT_LOGIN_EMPLOYEE = "AUTH_V2_LOGIN_EMPLOYEE"
EVENT_LOGIN_EMPLOYEE_LOCKED = "AUTH_V2_LOGIN_EMPLOYEE_LOCKED"
EVENT_LOGIN_PASSWORD_MIGRATION = "AUTH_V2_LOGIN_PASSWORD_MIGRATION"
EVENT_REFRESH = "AUTH_V2_REFRESH"
EVENT_REFRESH_REPLAY = "AUTH_V2_REFRESH_REPLAY"
EVENT_REFRESH_SESSION_FAMILY_WIPE = "AUTH_V2_REFRESH_SESSION_FAMILY_WIPE"
EVENT_LOGOUT = "AUTH_V2_LOGOUT"
EVENT_ME = "AUTH_V2_ME"
EVENT_PASSWORD_CHANGED_WEBHOOK = "AUTH_V2_PASSWORD_CHANGED_WEBHOOK"
EVENT_SESSION_REVOKED = "AUTH_V2_SESSION_REVOKED"
EVENT_SUPREME_CREATE = "AUTH_SUPREME_CREATE"
EVENT_SUPREME_LOGIN = "AUTH_SUPREME_LOGIN"

# Lock-state key types
LOCK_KEY_TYPE_MOBILE = "mobile"
LOCK_KEY_TYPE_LOGIN_EMPLOYEE = "login_employee"

# Revoke reason values (exact contract)
REVOKE_REASON_LOGOUT = "logout"
REVOKE_REASON_REPLAY = "replay"
REVOKE_REASON_PASSWORD_CHANGE = "password_change"
REVOKE_REASON_EMPLOYEE_INACTIVE = "employee_inactive"
REVOKE_REASON_SESSION_FAMILY_WIPE = "session_family_wipe"

ALLOWED_REVOKE_REASONS = {
    REVOKE_REASON_LOGOUT,
    REVOKE_REASON_REPLAY,
    REVOKE_REASON_PASSWORD_CHANGE,
    REVOKE_REASON_EMPLOYEE_INACTIVE,
    REVOKE_REASON_SESSION_FAMILY_WIPE,
}

HEADER_REQUEST_ID = "X-Request-ID"
HEADER_APP_VERSION = "X-App-Version"
HEADER_AUTHORIZATION = "Authorization"
HEADER_RETRY_AFTER = "Retry-After"
HEADER_RATE_LIMIT_LIMIT = "X-RateLimit-Limit"
HEADER_RATE_LIMIT_REMAINING = "X-RateLimit-Remaining"
HEADER_RATE_LIMIT_RESET = "X-RateLimit-Reset"

TOKEN_TYPE_ACCESS = "access"
TOKEN_TYPE_REFRESH = "refresh"
