"""Constants for the user management module."""

from __future__ import annotations

# ── Error codes ──────────────────────────────────────────────
USER_NOT_FOUND = "USER_NOT_FOUND"
USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
USER_INVALID_USERNAME = "USER_INVALID_USERNAME"
USER_INVALID_PASSWORD = "USER_INVALID_PASSWORD"
USER_SESSION_NOT_FOUND = "USER_SESSION_NOT_FOUND"
USER_SERVICE_UNAVAILABLE = "USER_SERVICE_UNAVAILABLE"
